service:
  name: imagegraph
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline

custom:
  s3:
    port: 4572 # Matches LocalStack
    directory: .s3rver-buckets
  S3RefsTableName: 'S3Refs-${self:provider.stage}'
  ImagesTableName: 'Images-${self:provider.stage}'
  CollectionsTableName: 'Collections-${self:provider.stage}'
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["S3RefsDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["ImagesDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["CollectionsDynamoDBTable", "Arn" ] }
  environment:
    IMAGES_TABLE: ${self:custom.ImagesTableName}

functions:
  graphql:
    handler: src/handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: src/handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: upload
    ImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: images
    S3RefsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: sha256
            AttributeType: S
        KeySchema:
          -
            AttributeName: sha256
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamEnabled: true
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:custom.S3RefsTableName}
    ImagesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: cuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: cuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.ImagesTableName}
    CollectionsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: cuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: cuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.CollectionsTableName}
